Make linting safe.
Sometimes linting crashes brunch process because of invalid coffeescript code.

```
node_modules/coffeelint-brunch/node_modules/coffee-script/lib/coffee-script/lexer.js:682
      throw SyntaxError("" + message + " on line " + (this.line + 1));
            ^
SyntaxError: unmatched OUTDENT on line 20
    at SyntaxError (unknown source)
```